Set-Location "C:\Projects\MindLab_Starter_Project"
Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"
$RepoRoot = "C:\Projects\MindLab_Starter_Project"
function Pause-Safe { Set-Location $RepoRoot; Read-Host "Press ENTER to continue (PowerShell stays open)" | Out-Null; Set-Location $RepoRoot }

# Governance if (!(Test-Path "C:\Projects\MindLab_Starter_Project\docs\planning\kids_certified\00_control\apply_snapshots_2026-04-14")) { New-Item -ItemType Directory -Force -Path "C:\Projects\MindLab_Starter_Project\docs\planning\kids_certified\00_control\apply_snapshots_2026-04-14" | Out-Null } # Snapshot source selection required before archive creation # Target archive: C:\Projects\MindLab_Starter_Project\docs\planning\kids_certified\00_control\apply_snapshots_2026-04-14\governance_snapshot.zip 
# Tracker if (!(Test-Path "C:\Projects\MindLab_Starter_Project\docs\planning\kids_certified\00_control\apply_snapshots_2026-04-14")) { New-Item -ItemType Directory -Force -Path "C:\Projects\MindLab_Starter_Project\docs\planning\kids_certified\00_control\apply_snapshots_2026-04-14" | Out-Null } # Snapshot source selection required before archive creation # Target archive: C:\Projects\MindLab_Starter_Project\docs\planning\kids_certified\00_control\apply_snapshots_2026-04-14\tracker_snapshot.zip 
# Release if (!(Test-Path "C:\Projects\MindLab_Starter_Project\docs\planning\kids_certified\00_control\apply_snapshots_2026-04-14")) { New-Item -ItemType Directory -Force -Path "C:\Projects\MindLab_Starter_Project\docs\planning\kids_certified\00_control\apply_snapshots_2026-04-14" | Out-Null } # Snapshot source selection required before archive creation # Target archive: C:\Projects\MindLab_Starter_Project\docs\planning\kids_certified\00_control\apply_snapshots_2026-04-14\release_snapshot.zip 
# Wave2 if (!(Test-Path "C:\Projects\MindLab_Starter_Project\docs\planning\kids_certified\00_control\apply_snapshots_2026-04-14")) { New-Item -ItemType Directory -Force -Path "C:\Projects\MindLab_Starter_Project\docs\planning\kids_certified\00_control\apply_snapshots_2026-04-14" | Out-Null } # Snapshot source selection required before archive creation # Target archive: C:\Projects\MindLab_Starter_Project\docs\planning\kids_certified\00_control\apply_snapshots_2026-04-14\wave2_snapshot.zip 
# Legacy if (!(Test-Path "C:\Projects\MindLab_Starter_Project\docs\planning\kids_certified\00_control\apply_snapshots_2026-04-14")) { New-Item -ItemType Directory -Force -Path "C:\Projects\MindLab_Starter_Project\docs\planning\kids_certified\00_control\apply_snapshots_2026-04-14" | Out-Null } # Snapshot source selection required before archive creation # Target archive: C:\Projects\MindLab_Starter_Project\docs\planning\kids_certified\00_control\apply_snapshots_2026-04-14\legacy_snapshot.zip 
# CrossAge if (!(Test-Path "C:\Projects\MindLab_Starter_Project\docs\planning\kids_certified\00_control\apply_snapshots_2026-04-14")) { New-Item -ItemType Directory -Force -Path "C:\Projects\MindLab_Starter_Project\docs\planning\kids_certified\00_control\apply_snapshots_2026-04-14" | Out-Null } # Snapshot source selection required before archive creation # Target archive: C:\Projects\MindLab_Starter_Project\docs\planning\kids_certified\00_control\apply_snapshots_2026-04-14\crossage_snapshot.zip 
Pause-Safe